"""MCP server that exposes the RAG system as tools for agents.

Any Model Context Protocol client (Claude Code, Claude Desktop, Cursor, LangChain/LangGraph agents
with an MCP adapter, ...) can discover and call three tools:

* ``search_code`` - hybrid retrieval, returns the best chunks with their GitHub links,
* ``ask_code``    - full RAG answer generated by the configured LLM, with sources,
* ``index_stats`` - what is indexed (repositories, chunk count, embedding model).

Two modes:

* **in-process** (default): the FAISS index in ``DATA_DIR`` is loaded into this process, no API
  container needed. Start with ``iu-rag-mcp`` or ``iu-rag mcp``.
* **remote**: set ``IU_RAG_API_URL`` (for example ``http://localhost:8000``) and every tool call is
  forwarded to the running HTTP API, so the Docker stack does the work.

Transport is stdio by default; set ``IU_RAG_MCP_TRANSPORT=streamable-http`` (and optionally
``IU_RAG_MCP_HOST`` / ``IU_RAG_MCP_PORT``) to serve over HTTP instead.
"""

from __future__ import annotations

import json
import os
from functools import lru_cache
from typing import Any

import httpx
from mcp.server.mcpserver import MCPServer  # mcp >= 2 (was FastMCP in mcp 1.x)

from .config import get_settings

INSTRUCTIONS = (
    "Tools over a code search index of the GitHub repositories of the developer Chantifa and of the "
    "IU International University of Applied Sciences (organisation iubh). Use search_code first and "
    "cite the returned owner/repo/path sources in your answer."
)

mcp = MCPServer("iu-code-rag", instructions=INSTRUCTIONS)


def _api_url() -> str | None:
    """Base URL of a running HTTP API when remote mode is configured, else ``None``."""
    url = os.environ.get("IU_RAG_API_URL", "").strip()
    return url.rstrip("/") or None


@lru_cache(maxsize=1)
def _pipeline():
    """Load the in-process RAG pipeline from the on-disk index once and cache it."""
    from .chain import RagPipeline

    return RagPipeline.from_index(get_settings())


def _post(path: str, payload: dict[str, Any]) -> dict[str, Any]:
    """POST ``payload`` to the remote API and return the decoded JSON body."""
    r = httpx.post(f"{_api_url()}{path}", json=payload, timeout=300)
    r.raise_for_status()
    return r.json()


def _format_results(results: list[dict[str, Any]]) -> str:
    """Render search hits as markdown blocks: a linked header line followed by the chunk text."""
    if not results:
        return "No matching code found in the indexed repositories."
    blocks = []
    for i, x in enumerate(results, 1):
        header = f"[{i}] {x['source']}"
        if x.get("url"):
            header += f" <{x['url']}>"
        if x.get("score") is not None:
            header += f" (score {x['score']})"
        blocks.append(f"{header}\n{x['content']}")
    return "\n\n".join(blocks)


def search_code(query: str, k: int = 5) -> str:
    """Search Chantifa's GitHub projects and the IU (iubh) course repositories for code and docs.

    Hybrid retrieval (embeddings + BM25) over Python, Java, JavaScript, notebooks, Markdown and
    more. Returns the ``k`` most relevant chunks, each with its ``owner/repo/path`` source and a
    GitHub link, so the caller can cite them. Use this before answering questions about the
    repositories.
    """
    k = max(1, min(int(k), 20))
    if _api_url():
        results = _post("/search", {"query": query, "k": k})["results"]
    else:
        results = [
            {
                "source": d.metadata["source"],
                "url": d.metadata.get("url"),
                "score": d.metadata.get("score"),
                "content": d.page_content,
            }
            for d in _pipeline().search(query, k=k)
        ]
    return _format_results(results)


def ask_code(question: str, k: int = 6) -> str:
    """Answer a question about the repositories with the RAG system's own language model.

    Retrieves the ``k`` best chunks and lets the configured LLM (Ollama, Anthropic, or the
    extractive fallback) write an answer that cites ``[owner/repo/path]`` sources. Slower than
    ``search_code``; prefer ``search_code`` when the calling agent can reason over raw snippets itself.
    """
    k = max(1, min(int(k), 20))
    if _api_url():
        data = _post("/ask", {"question": question, "k": k})
    else:
        data = _pipeline().ask(question, k=k).to_dict()
    sources = "\n".join(f"- {s['source']} <{s['url']}>" for s in data.get("sources", []))
    return f"{data['answer']}\n\nSources:\n{sources}" if sources else data["answer"]


def index_stats() -> str:
    """Describe the current index: repositories, number of documents and chunks, embedding model."""
    if _api_url():
        r = httpx.get(f"{_api_url()}/stats", timeout=60)
        r.raise_for_status()
        meta = r.json()
    else:
        meta = _pipeline().index_meta
    return json.dumps(meta, indent=2, ensure_ascii=False)


mcp.tool()(search_code)
mcp.tool()(ask_code)
mcp.tool()(index_stats)


def main() -> None:
    """Entry point of ``iu-rag-mcp``: run the server on stdio (default) or streamable HTTP."""
    transport = os.environ.get("IU_RAG_MCP_TRANSPORT", "stdio")
    if transport == "stdio":
        mcp.run()
    else:
        mcp.run(
            transport,  # type: ignore[arg-type]
            host=os.environ.get("IU_RAG_MCP_HOST", "127.0.0.1"),
            port=int(os.environ.get("IU_RAG_MCP_PORT", "8765")),
        )


if __name__ == "__main__":
    main()
